feat: CP-9461 wallet_addNetwork
ava-labs/core-extension pull request #108
Opened 2024-12-10 18:48 UTC by vvava

## Description

## Changes

## Testing

## Screenshots:

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [ ] I've tested the changes myself before sending it to code review and QA.

2024-12-13 09:51 UTC, gergelylovas commented on src/background/connections/middlewares/ActiveNetworkMiddleware.ts
> +    if (!isNetworkNeeded(method)) {
Please update the tests as well

2024-12-13 09:51 UTC, gergelylovas commented on src/background/connections/middlewares/DAppRequestHandlerMiddleware.ts
> +      console.log('module: ', module);
Please remove

2024-12-13 09:53 UTC, gergelylovas commented on src/background/connections/middlewares/PermissionMiddleware.ts
> +  'hvm_signTransaction',
We should not need to list the module handled RPC methods since it will not be dynamic. Any PRC change in the module would need to be listed here as well.

2024-12-13 09:53 UTC, gergelylovas commented on src/background/connections/middlewares/PermissionMiddleware.ts
> +  'hvm_signTransaction',
I think we can omit the `hvm_` prefix. The request scope will determine the network anyways

2024-12-13 09:56 UTC, gergelylovas commented on src/background/providers/ChainAgnosticProvider.ts
> +          );
This should be in the chain specific providers and not here. We should ensure that the `request` method of the Chain agnostic provider is always called with a CAIP chainID

2024-12-13 09:57 UTC, gergelylovas commented on src/background/services/network/NetworkService.ts
> +
Should we handle this in the handler instead? Populating the chain ID I mean.

2024-12-13 09:58 UTC, gergelylovas commented on src/background/vmModules/ModuleManager.ts
> +    // console.log('caipId: ', caipId);
Please remove

2024-12-13 09:59 UTC, gergelylovas commented on src/background/services/secrets/SecretsService.ts
> +        [NetworkVMType.HVM]: getAddressFromXPub(secrets.xpub, index),
This should not be merged like this otherwise we may end up with accounts with wrong addresses saved in storage. 
Please either leave `NetworkVMType.HVM` empty or implement the correct method.

2024-12-13 10:00 UTC, gergelylovas commented on src/background/services/network/models.ts
> +export interface AddNetworkPayload {
Let's move this definition into the handler's file to ensure we are not reusing it elsewhere in our codebase.

2024-12-13 10:02 UTC, gergelylovas commented on package.json
> +    "@avalabs/avalanche-module": "0.0.0-feat-CP-9461-create-hvm-module-20241210153705",
We should update these before merging.

2024-12-13 10:05 UTC, gergelylovas commented on src/background/services/network/handlers/wallet_addNetwork.ts
> +    const isCustomNetworkExist = await this.networkService.getNetwork(chainId);
getNetwork supports the caipId as well lets pass that instead.

2024-12-13 10:09 UTC, gergelylovas commented on src/background/services/network/models.ts
> +  caipId?: string;
`caipId` is already optional in the Network type. We can remove this line

2025-01-17 16:58 UTC, gergelylovas requested changes

2025-01-17 16:58 UTC, gergelylovas commented on src/background/services/wallet/WalletService.ts
> +    }
Please add tests for the HVM specific paths

2025-01-17 16:58 UTC, gergelylovas commented on src/background/services/accounts/handlers/avalanche_getAccountPubKey.ts
> +    return this.handleAuthenticated({ request });
Do we want to open it up for the world? If we do this, any dapp can query the addresses of the wallet without user consent.

2025-01-17 16:58 UTC, gergelylovas commented on src/background/vmModules/ModuleManager.ts
> +  async #getModule(scope: string): Promise<Module | undefined> {
It's not always a scope. Seems like it can be chainID as well. We either should prevent that from happening or rename the param to something like `chainIdOrScope`

2025-01-17 16:58 UTC, gergelylovas commented on src/background/vmModules/ModuleManager.ts
> +      new HvmModule({
Please update the tests for this file to test the new changes as well.

2025-01-17 16:58 UTC, gergelylovas commented on src/background/services/secrets/utils/getAddressForHvm.test.ts
> +describe('getAddressForHvm()', () => {
Please use full path like in other test files

2025-01-17 16:58 UTC, gergelylovas commented on src/background/services/secrets/utils/getAccountPrivateKeyFromMnemonic.test.ts
> +describe('getAccountPrivateKeyFromMnemonic(', () => {
Please use full path like in other test files

2025-01-17 16:58 UTC, gergelylovas commented on src/background/services/secrets/SecretsService.ts
> +          secrets.secretType === SecretType.Mnemonic
Please add tests for the new sections.

2025-01-21 20:11 UTC, gergelylovas approved these changes

2025-01-21 20:11 UTC, gergelylovas commented on src/background/connections/dAppConnection/models.ts
> +  // TODO: rename to wallet
please remove the comment

2025-01-22 13:27 UTC, gergelylovas approved these changes

2025-01-23 10:06 UTC, meeh0w approved these changes
I've tested and it worked as described :+1:

Some thoughts for the future (I don't think we need those right now):

1. We could add the HVM address to the account details screen: 
![image](https://github.com/user-attachments/assets/66209907-fd67-428a-becd-c56886e2eb1a)
2. We could decode the `memo` on the approval screen

2025-01-23 10:12 UTC, merged