fix: address onboarding UI deviations
ava-labs/core-extension pull request #24
Opened 2024-08-07 02:32 UTC by ryanml

## Description
Fixes the onboarding UI design deviations described in: https://ava-labs.atlassian.net/browse/CP-8979

## Testing
Verify the five items in the issue

## Screenshots:
<img width="863" alt="Screenshot 2024-08-06 at 7 20 10 PM" src="https://github.com/user-attachments/assets/621e277f-bc41-473f-9a75-55d5ddf3bc9d">

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [x] I've tested the changes myself before sending it to code review and QA.

2024-08-07 02:33 UTC, ryanml commented on src/pages/Onboarding/pages/Seedless/components/ExistingWalletButton.tsx
> +        backgroundColor: 'rgba(88, 88, 91, 0.75)',
Using explicit values with `rgba` to make sure the text is not transparent, only the background

2024-08-08 13:17 UTC, vvava approved these changes

2024-08-09 15:59 UTC, bferenc approved these changes

2024-08-12 14:53 UTC, vvava requested changes

2024-08-12 14:53 UTC, vvava commented on src/pages/Onboarding/pages/Seedless/components/ExistingWalletOptions.tsx
> +        <img
change to k2 icon

2024-08-12 19:23 UTC, vvava approved these changes
nice job with changing the icon!

2024-08-12 21:09 UTC, bferenc approved these changes

2024-08-13 09:11 UTC, vvava approved these changes

2024-08-13 09:11 UTC, merged