Feat/cp 8368 historyservice
ava-labs/core-extension pull request #42
Opened 2024-09-10 14:35 UTC by vvava

## Description

## Changes

## Testing

## Screenshots:

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [ ] I've tested the changes myself before sending it to code review and QA.

2024-09-11 13:29 UTC, meeh0w reviewed
I know it's still a draft, but just wanted to leave my thoughts:

I liked how @gergelylovas got rid of different types of balances services and only left one `BalancesService`. Can we do the same with the `HistoryService`s?

For reference, here's the link to his `BalancesService`:
* https://github.com/ava-labs/core-extension/pull/43/files#diff-fd411839e9eef1b07f0b63cedd78196b77fdca273ec67f9d25a54070ba6435d8

We could essentially be left with just `HistoryService` here that could load specific module for a given network and invoke `getTransactionHistory()` on it.

2024-09-11 15:49 UTC, vvava commented
> I know it's still a draft, but just wanted to leave my thoughts:
> 
> I liked how @gergelylovas got rid of different types of balances services and only left one `BalancesService`. Can we do the same with the `HistoryService`s?
> 
> For reference, here's the link to his `BalancesService`:
> 
> * https://github.com/ava-labs/core-extension/pull/43/files#diff-fd411839e9eef1b07f0b63cedd78196b77fdca273ec67f9d25a54070ba6435d8
> 
> We could essentially be left with just `HistoryService` here that could load specific module for a given network and invoke `getTransactionHistory()` on it.

good point, thanks!

2024-09-13 06:40 UTC, meeh0w commented on src/background/services/history/HistoryService.ts
> +      return { ...transaction, vmType, isBridge };
Is there a reason we cannot use `network.vmType`? What about other network types? (`#getVmType` only works for X/P chains).

2024-09-13 06:45 UTC, meeh0w commented on src/background/services/history/HistoryService.ts
> +    const module = await this.moduleManager.loadModuleByNetwork(network);
This line can throw an error, I guess we could use `resolve()` here:

```suggestion
    const [module] = await resolve(this.moduleManager.loadModuleByNetwork(network));
    
    if (!module) {
      sentryCaptureException(
        new Error(`Fetching history failed. Module not found for ${network.caipId}`),
        SentryExceptionTypes.VM_MODULES
      );
      return [];
    }
```

2024-09-13 06:47 UTC, meeh0w commented on src/background/vmModules/ModuleManager.ts
> +          },
`ApprovalController` already exists :)

```suggestion
        approvalController: this.#approvalController,
```

2024-09-13 06:47 UTC, meeh0w commented on src/background/vmModules/ModuleManager.ts
> +        },
`ApprovalController` already exists :)

```suggestion
        approvalController: this.#approvalController,
```

2024-09-13 06:48 UTC, meeh0w commented on src/background/vmModules/mocks/avm.manifest.json
Is it intentional to add this and `pvm.manifest.json` files back? I think we don't need `mocks` directory anymore :)

2024-09-13 06:58 UTC, meeh0w commented on package.json
> +    "@avalabs/evm-module": "0.5.0",
Latest versions for vm modules are already `0.7.0` :) same for `vm-module-types`.

2024-09-13 06:59 UTC, meeh0w commented on src/__mocks__/@blockaid/client.ts
I believe this is sorted by already existing `__mocks__/@blockaid/client.ts`

2024-09-13 07:00 UTC, meeh0w commented on src/pages/Wallet/components/History/components/ActivityCard/ActivityCardIcon.tsx
> +    // TODO: check the vmmodules for the type
Is this comment still needed?

2024-09-13 07:34 UTC, meeh0w requested changes
I also took for tor a quick test and found filtering for `Bridge` in activity tab doesn't seem to work. Posted suggestions for fixes below :)

2024-09-13 07:34 UTC, meeh0w commented on src/pages/Wallet/WalletRecentTxs.tsx
> +      return tx.isContractCall && tx.txType !== TransactionType.SWAP;
```suggestion
      return tx.isContractCall && !tx.isBridge && tx.txType !== TransactionType.SWAP;
```

2024-09-13 07:34 UTC, meeh0w commented on src/pages/Wallet/WalletRecentTxs.tsx
> +      return tx.txType === TransactionType.BRIDGE;
```suggestion
      return tx.isBridge || tx.txType === TransactionType.BRIDGE;
```

2024-09-13 17:31 UTC, meeh0w approved these changes

2024-09-13 17:32 UTC, gergelylovas approved these changes

2024-09-13 17:33 UTC, merged