feat: CP-9258 add new calculation
ava-labs/core-extension pull request #62
Opened 2024-10-04 17:24 UTC by vvava

## Description

WIP

## Changes

## Testing

## Screenshots:

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [ ] I've tested the changes myself before sending it to code review and QA.

2024-10-14 18:31 UTC, meeh0w requested changes
Looks great! I left just a small comment, I think we can simplify it even more :)

2024-10-14 18:31 UTC, meeh0w commented on src/background/services/networkFee/NetworkFeeService.test.ts
> +    it.only('provides base information and three rate presets', async () => {
```suggestion
    it('provides base information and three rate presets', async () => {
```

2024-10-14 18:31 UTC, meeh0w commented on src/background/services/networkFee/NetworkFeeService.ts
> +    const module = await this.moduleManager.loadModuleByNetwork(network);
I think these `vmName` conditions can be removed entirely. `.getNetworkFee()` response has the same shape for all VM modules.

2024-10-25 08:11 UTC, meeh0w approved these changes

2024-10-28 13:59 UTC, bferenc approved these changes

2024-10-28 19:04 UTC, merged