feat: add default tokens to swap
ava-labs/core-extension pull request #84
Opened 2024-10-28 19:06 UTC by vvava

## Description

We want to add default tokens to the Swap page

## Changes

Set the AVAX and USDC tokens as default transaction pairs.

## Testing

Go to the swap page -> you should see the AVAX in the `from` and the USDC in the `to` field -> swap should work as before

## Screenshots:

https://github.com/user-attachments/assets/0cc4998b-7627-4284-ad56-e807c69cd9ba

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [x] I've tested the changes myself before sending it to code review and QA.

2024-10-29 08:07 UTC, meeh0w requested changes

2024-10-29 08:07 UTC, meeh0w commented on src/pages/Swap/Swap.tsx
> +        toToken: USDC_TOKEN,
Not related to this PR, but the fact we need to provide `token`, `fromToken` and `toToken` here breaks my brain. 🤯 Why three values!? 😂

2024-10-29 08:07 UTC, meeh0w commented on src/pages/Swap/Swap.tsx
> +    if (!selectedFromToken && !selectedToToken) {
This check alone does not quite work, tokens are not restored when I close and re-open extension.

### Prod build:

https://github.com/user-attachments/assets/11e866de-ffec-499f-8af0-28aa140a065c


### This branch:

https://github.com/user-attachments/assets/b4f6887e-925c-4b59-87f2-b14a2eb94d14

2024-10-31 10:55 UTC, meeh0w requested changes
There is still something wrong with remembering the values. It sometimes works and sometimes doesn't. There's probably a race condition somewhere.

https://github.com/user-attachments/assets/24f14d30-a466-4cc4-9480-850f3a19c74b

2024-10-31 16:29 UTC, vvava commented
> There is still something wrong with remembering the values. It sometimes works and sometimes doesn't. There's probably a race condition somewhere.
> 
>  Screen.Recording.2024-10-31.at.11.53.19.mov

Yeah, something is wrong there, I'm fixing it

2024-11-06 17:45 UTC, meeh0w approved these changes
Looks like it's working now 👏

2024-11-06 20:19 UTC, bferenc approved these changes

2024-11-08 18:02 UTC, merged