feat: CP-9472 add duplicated account dialog
ava-labs/core-extension pull request #90
Opened 2024-11-14 08:59 UTC by vvava

## Description

## Changes

## Testing

## Screenshots:

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [ ] I've tested the changes myself before sending it to code review and QA.

2024-11-15 14:20 UTC, gergelylovas requested changes

2024-11-15 14:20 UTC, gergelylovas commented on src/background/services/wallet/handlers/importLedger.ts
> +        },
Let's try to preserve the same response type as the success message normally has.
```suggestion
        result: {
          id: '0',
          name,
          type: secretType,
        },
```

2024-11-15 14:20 UTC, gergelylovas commented on src/background/services/wallet/handlers/models.ts
> +  onlyCheckWalletIsExist?: boolean;
Should we call this `dryRun` instead? 
```suggestion
  dryRun?: boolean;
```

2024-11-15 14:20 UTC, gergelylovas commented on src/pages/ImportPrivateKey/ImportPrivateKey.tsx
> +  console.log('allAccounts: ', allAccounts);
Please remove

2024-11-15 14:20 UTC, gergelylovas commented on src/components/ledger/LedgerConnector.tsx
> +  checkWalletIsExist?: boolean;
```suggestion
  checkWalletExists?: boolean;
```

2024-11-25 09:53 UTC, bferenc requested changes
Works great! 👍 
Can we standardize the names though? Currently there are multiple cases like "checkWalletExists", "isLedgerExists", "checkLedgerWalletIsExist"

2024-11-26 15:45 UTC, bferenc approved these changes
Tested as well ✅

2024-12-02 12:34 UTC, meeh0w requested changes

2024-12-02 12:34 UTC, meeh0w commented on src/pages/ImportPrivateKey/ImportPrivateKey.tsx
> +  const [isDuplicatedAccountDialogOpen, setIsDuplicatedDialogDialogOpen] =
```suggestion
  const [isDuplicatedAccountDialogOpen, setIsDuplicatedAccountDialogOpen] =
```

2024-12-02 12:34 UTC, meeh0w commented on src/pages/ImportPrivateKey/ImportPrivateKey.tsx
> +  const checkAccount = useCallback(
```suggestion
  const checkIfAccountExists = useCallback(
```

2024-12-02 12:34 UTC, meeh0w commented on src/components/ledger/LedgerConnector.tsx
> +        throw new Error('wallet already exists');
We should check the error message - there are other reasons `importLedger(...)` could fail.

2024-12-02 12:34 UTC, meeh0w commented on src/components/ledger/LedgerConnector.tsx
> +  isWalletExist,
If I understand correctly, this prop tells `LedgerConnector` to verify if the secret already exists, right?

If so, I think we should rename it. Right now it sounds more as a statement than a question/request to check for something.

Maybe: `checkIfWalletExists` or `withWalletDeduplicationWarning` ?

2024-12-04 15:13 UTC, meeh0w approved these changes

2024-12-04 15:15 UTC, bferenc approved these changes

2024-12-04 15:19 UTC, meeh0w commented
(I also tested, btw.)

2024-12-04 18:52 UTC, bferenc approved these changes

2024-12-05 08:37 UTC, meeh0w approved these changes

2024-12-05 09:51 UTC, merged