feaT: CP-9487 CP-9473 ledger flow
ava-labs/core-extension pull request #93
Opened 2024-11-19 19:02 UTC by vvava

## Description
We want to polish a bit our ledger wallet flow:
1. We want to show the addresses with a balance or the first 3 addresses
2. If the user has no ledger device detected, give the user the opportunity to close the page and reopen the extension

## Changes

Address list displaying and the extension reopen.

## Testing

Go to account page -> try to add a ledger wallet with a ledger connected and without that.

## Screenshots:

https://github.com/user-attachments/assets/510721e6-58da-4d9d-828b-ba2cb1b4f0d3

https://github.com/user-attachments/assets/cb34bfce-d619-4af5-8cef-43ba4cb094f1

## Checklist for the author

Tick each of them when done or if not applicable.

- [ ] I've covered new/modified business logic with Jest test cases.
- [x] I've tested the changes myself before sending it to code review and QA.

2024-11-25 10:11 UTC, bferenc requested changes
Thanks, left some comments and have 2 additional questions:
- is this based on https://github.com/ava-labs/core-extension/pull/90? If so, can you please update this branch and compare it against that one?
- so we simply hide the 0 balance addresses during onboarding?
  - what if none of the first 3 accounts have balances?
  - shouldn't we stop when an account has 0 balance? (e.g.: don't show 3rd account if the 2nd doesn't have AVAX)
  - is it expected to still onboard with all 3 public keys for LEDGER_LIVE regardless of their balances?

2024-11-25 10:11 UTC, bferenc commented on src/background/runtime/BackgroundRuntime.ts
> -    private bridgeService: BridgeService,
Wasn't this intentionally left here?

2024-11-25 10:11 UTC, bferenc commented on src/background/services/balances/handlers/getAvaxBalance.ts
> +    console.log('balances: ', balances);
Isn't the `unable to fetch balance` error enough?

```suggestion
```

2024-11-26 10:18 UTC, vvava commented
> Thanks, left some comments and have 2 additional questions:
> 
> * is this based on [feat: CP-9472 add duplicated account dialog #90](https://github.com/ava-labs/core-extension/pull/90)? If so, can you please update this branch and compare it against that one?
> * so we simply hide the 0 balance addresses during onboarding?
>   
>   * what if none of the first 3 accounts have balances?
>   * shouldn't we stop when an account has 0 balance? (e.g.: don't show 3rd account if the 2nd doesn't have AVAX)
>   * is it expected to still onboard with all 3 public keys for LEDGER_LIVE regardless of their balances?

It is based on that ticket yes, I will revisit if I will able to merge in to the main.

```
AC1: when the user is connecting a Ledger only show the accounts with a C-Chain balance

if that is 1 account show one, if there are 3 accounts show 3

cap the forward look at 3 accounts 
```

As I understand the ticket we should display the addresses with any balance to the user up to three addresses (so if the 1st and the 3rd accounts have some AVAX we should hide only the 2nd one but not to stop getting the 3rd address). If we cannot find any balances we should show all the three addresses as we are doing at the moment.  
I don't think we need to do any other changes about the current behaviour of the onboarding / adding a new ledger wallet.

2024-11-26 10:21 UTC, vvava commented on src/background/runtime/BackgroundRuntime.ts
> -    private bridgeService: BridgeService,
I'm not sure, it was not used anywhere so it seemed to be just hanging there as an unnecessary dependency.

2024-11-26 16:38 UTC, bferenc commented on src/background/runtime/BackgroundRuntime.ts
> -    private bridgeService: BridgeService,
I guess it was left there to attempt to fetch the bridge configs as soon as possible. Do you mind restoring it?

2024-12-04 09:12 UTC, bferenc reviewed
Can you fix the merge conflict, please?

2024-12-04 18:54 UTC, bferenc submitted a review, later dismissed

2024-12-05 10:40 UTC, meeh0w requested changes

2024-12-05 10:40 UTC, meeh0w commented on src/background/runtime/BackgroundRuntime.ts
> +import { BridgeService } from '@avalabs/bridge-unified';
```suggestion
import { BridgeService } from '../services/bridge/BridgeService';
```

2024-12-05 10:40 UTC, meeh0w commented on src/pages/Accounts/AddWalletWithLedger.tsx
> +                          browser.action.openPopup();
This is a great addition! Let's also do it on the success screen, when users click "Close" 🎉

2024-12-05 10:59 UTC, meeh0w approved these changes

2024-12-05 11:00 UTC, bferenc approved these changes

2024-12-05 11:05 UTC, merged